Update version to match npm
heroku/heroku-nodejs-plugin pull request #110
Opened 2023-11-09 16:14 UTC by colincasey

This package is not actively published to npm.  Instead, new [releases](https://github.com/heroku/heroku-nodejs-plugin/releases) are versioned incrementally (`v11`, `v12`, `v13`, ...) and added as vendored packages to the [heroku/nodejs](https://github.com/heroku/heroku-buildpack-nodejs) buildpack.

But:
* we did publish a single release to npm so that the name `heroku-nodejs-plugin` in order to claim this package name and prevent some other malicious package from publishing under this name
* this published version is reported as `0.1.3`

This can cause some confusion because the version for this package in the `main` branch is `0.1.0` which does not match the version published to npm (`0.1.3`).  Furthermore, there is an [outdated Synk vulnerability report for `heroku-nodejs-plugin@0.1.0` ](https://security.snyk.io/vuln/SNYK-JS-HEROKUNODEJSPLUGIN-2934433) that adds to the confusion around this package.

Bumping the current version on `main` to `0.1.3` would at least align the valid package we have on npm with this repository (even if we don't plan to publish newer versions there) and avoid matching the same version in the outdated Synk report.

Going forward we should revisit:
* the use of incremental versioning instead of semver so that we could have a version listed in package.json that is consistent
* publishing new versions to npm even if we still vendor them into the [heroku/nodejs](https://github.com/heroku/heroku-buildpack-nodejs) buildpack

2023-11-09 16:35 UTC, edmorley requested changes
I think we should:
1. Set `private` to `true` in `package.json`
2. Rename the package `name` to something under the `@heroku/*` namespace. 
3. Intentionally NOT publish to the new name
4. Mark the old package on npmjs.org as yanked/obsolete

The above should prevent security tools from inadvertently trying to compare the vendored package to some random package on npmjs.org.

Without the rename, these tools will still associate the two, and mean they still report false positives.

2023-11-09 16:37 UTC, edmorley commented
Plus I think we should either change the `package.json` `version` to match the versions here:
https://github.com/heroku/heroku-nodejs-plugin/releases
(ie: `14.0.0` etc.)

Or else make the `package.json` `version` (of the newly renamed package) something obviously not-incremented, like `0.0.0`.

If we go with a real version, we should also update the release scripts and/or playbook to cover making the edits to `package.json`.

2023-11-13 11:29 UTC, edmorley commented
We should also click the "Found a mistake" button on https://security.snyk.io/vuln/SNYK-JS-HEROKUNODEJSPLUGIN-2934433 to report it as a false positive.

2024-02-05 14:30 UTC, colincasey commented
Closing since we've decided to archive this repo (#116)

2024-02-05 14:30 UTC, closed without merging